development:
  #adapter: async
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TEMPORARY_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: wander_production
  ssl_params:
    verify_mode: OpenSSL::SSL::VERIFY_NONE

